import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import guestRouter from "./guest";
import operatorRevealRouter from "./operator-reveals";
import operatorVaultsRouter from "./operator-vaults";
import operatorReportsRouter from "./operator-reports";
import billingRouter from "./billing";
import giftRouter from "./gifts";
import adminBillingRouter from "./admin-billing";
import emailRouter from "./email";
import adminVaultsRouter from "./admin-vaults";
import adminLifecycleRouter from "./admin-lifecycle";
import adminExportRouter from "./admin-export";
import adminContentRouter from "./admin-content";
import adminBackupRouter from "./admin-backup";
import legalRouter from "./legal";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(legalRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(guestRouter);
router.use(operatorRevealRouter);
router.use(operatorVaultsRouter);
router.use(operatorReportsRouter);
router.use(billingRouter);
router.use(giftRouter);
router.use(adminBillingRouter);
router.use(emailRouter);
router.use(adminVaultsRouter);
router.use(adminLifecycleRouter);
router.use(adminExportRouter);
router.use(adminContentRouter);
router.use(adminBackupRouter);

export default router;
